#ifndef __GPIO_DEFINES_H__
#define __GPIO_DEFINES_H__
#define GPIO_ADDRESS 0x80008000
#define GPIO_SIZE 0x1000
#define GPIO_SET_REG_OFFS 0x8
#define GPIO_VALUE_REG_OFFS 0x0
#define GPIO_OUTPUT_ENABLE_REG_OFFS 0x4
#define GPIO_CLEAR_REG_OFFS 0xc
#endif /* __GPIO_DEFINES_H__ */